### get a menu of all the restaurants for today
GET http://localhost:8080/topjava15graduation/rest/menu
Authorization: Basic user@yandex.ru password

### vote for restaurant with id 100008
PUT http://localhost:8080/topjava15graduation/rest/menu/100008/vote
Authorization: Basic user@yandex.ru password


### get restaurant by id
GET http://localhost:8080/topjava15graduation/rest/restaurants/100003
Authorization: Basic admin@gmail.com admin

### get all restaurants
GET http://localhost:8080/topjava15graduation/rest/restaurants
Authorization: Basic admin@gmail.com admin

### create restaurant
POST http://localhost:8080/topjava15graduation/rest/restaurants
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{"name":"New"}

### delete restaurant
DELETE http://localhost:8080/topjava15graduation/rest/restaurants/100005
Authorization: Basic admin@gmail.com admin

### update restaurant
PUT http://localhost:8080/topjava15graduation/rest/restaurants/100003
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{"name":"Mama Roma Updated"}

### get a menu of restaurant with id 100003 for today
GET http://localhost:8080/topjava15graduation/rest/restaurants/100003/menu
Authorization: Basic admin@gmail.com admin

### update menu of restaurant with id 100003 for today
PUT http://localhost:8080/topjava15graduation/rest/restaurants/100003/menu
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "dishes": [
        {
            "name": "Пельмени",
            "price": 77700
        },
        {
            "name": "Борщ",
            "price": 11100
        }
    ]
}

### update menu of restaurant with id 100003 for another day
PUT http://localhost:8080/topjava15graduation/rest/restaurants/100003/menu?date=2020-01-01
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "dishes": [
        {
            "name": "Пельмени",
            "price": 55500
        }
    ]
}

### get a menu of restaurant with id 100003 for date 2018-12-11
GET http://localhost:8080/topjava15graduation/rest/restaurants/100003/menu?date=2018-12-11
Authorization: Basic admin@gmail.com admin

###
